Spring:
  datasource:
    url: YOUR_DATABASE_URL
    username : YOUR_USERNAME
    password: YOUR_PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  ai:
    vertex:
      ai:
        gemini:
          project-id: feelpick
          location: asia-northeast3

file:
  dir: YOUR_FILE_DIR_PATH

logging:
  level:
    org.hibernate.SQL: debug